N = int(input('INFORME UM NÚMERO PARA VOCÊ VER A TABUADA: '))

print('----------------------------------')
print('----- TABUADA MULTIPLICAÇÃO -----')
print('{} X {}  = {}'.format(N,1,N*1))
print('{} X {}  = {}'.format(N,2,N*2))
print('{} X {}  = {}'.format(N,3,N*3))
print('{} X {}  = {}'.format(N,4,N*4))
print('{} X {}  = {}'.format(N,5,N*5))
print('{} X {}  = {}'.format(N,6,N*6))
print('{} X {}  = {}'.format(N,7,N*7))
print('{} X {}  = {}'.format(N,8,N*8))
print('{} X {}  = {}'.format(N,9,N*9))
print('{} X {} = {}'.format(N,10,N*10))

print('----------------------------------')
print('----- TABUADA DE ADIÇÃO -----')
print('{} + {}  = {}'.format(N,1,N+1))
print('{} + {}  = {}'.format(N,2,N+2))
print('{} + {}  = {}'.format(N,3,N+3))
print('{} + {}  = {}'.format(N,4,N+4))
print('{} + {}  = {}'.format(N,5,N+5))
print('{} + {}  = {}'.format(N,6,N+6))
print('{} + {}  = {}'.format(N,7,N+7))
print('{} + {}  = {}'.format(N,8,N+8))
print('{} + {}  = {}'.format(N,9,N+9))
print('{} + {} = {}'.format(N,10,N+10))

print('----------------------------------')
print('----- TABUADA DE SUBTRAÇÃO -----')
print('{} - {}  = {}'.format(N,1,N-1))
print('{} - {}  = {}'.format(N,2,N-2))
print('{} - {}  = {}'.format(N,3,N-3))
print('{} - {}  = {}'.format(N,4,N-4))
print('{} - {}  = {}'.format(N,5,N-5))
print('{} - {}  = {}'.format(N,6,N-6))
print('{} - {}  = {}'.format(N,7,N-7))
print('{} - {}  = {}'.format(N,8,N-8))
print('{} - {}  = {}'.format(N,9,N-9))
print('{} - {} = {}'.format(N,10,N-10))

print('----------------------------------')
print('----- TABUADA DE DIVISÃO -----')
print('{} /  {} = {:.2f}'.format(N,1,N/1))
print('{} /  {} = {:.2f}'.format(N,2,N/2))
print('{} /  {} = {:.2f}'.format(N,3,N/3))
print('{} /  {} = {:.2f}'.format(N,4,N/4))
print('{} /  {} = {:.2f}'.format(N,5,N/5))
print('{} /  {} = {:.2f}'.format(N,6,N/6))
print('{} /  {} = {:.2f}'.format(N,7,N/7))
print('{} /  {} = {:.2f}'.format(N,8,N/8))
print('{} /  {} = {:.2f}'.format(N,9,N/9))
print('{} / {} = {:.2f}'.format(N,10,N/10))
print('----------------------------------')